services:
  - type: web
    name: sandopmvp
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sandopmvp-db
          property: connectionString

databases:
  - name: sandopmvp-db
    plan: free
    databaseName: sandopmvp
    user: sandopmvp
